version: '2'
services:
  debug:
    container_name: gateaas-debug
    image: ealen/echo-server:0.5.1
    ports:
      - 8085:80
  input-a:
    image: gateaas:1.0.0
    container_name: gateaas-halfadder-input-a
    ports:
      - "8086:80"
    environment:
     - PORT=80
     - BIND_ADDRESS=0.0.0.0
     - GATE_TYPE=NOOP
     - >
       OUTPUTS=
       http://carry/in/0,
       http://sum/in/0,
       http://debug/input-a       
  input-b:
    image: gateaas:1.0.0
    container_name: gateaas-halfadder-input-b
    ports:
      - "8087:80"
    environment:
     - PORT=80
     - BIND_ADDRESS=0.0.0.0
     - GATE_TYPE=NOOP
     - OUTPUTS=http://gateaas-halfadder-carry/in/1,http://gateaas-halfadder-sum/in/1
  carry:
    image: gateaas:1.0.0
    container_name: gateaas-halfadder-carry
    environment:
     - PORT=80
     - BIND_ADDRESS=0.0.0.0
     - GATE_TYPE=AND
     - OUTPUTS=http://debug/carry
  sum:
    image: gateaas:1.0.0
    container_name: gateaas-halfadder-sum
    environment:
     - PORT=80
     - BIND_ADDRESS=0.0.0.0
     - GATE_TYPE=XOR
     - OUTPUTS=http://debug/sum

